const jokes = [
  "Why don't scientists trust atoms? Because they make up everything.",
  "Did you hear about the mathematician who's afraid of negative numbers? He'll stop at nothing to avoid them.",
  "How do you organize a space party? You 'planet'!",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "Why don't skeletons fight each other? They don't have the guts.",
  "What do you call a bear with no teeth? A gummy bear.",
  "How do you make a tissue dance? You put a little boogie in it.",
  "Did you hear about the cheese factory that exploded? There was nothing left but de-brie.",
  "Why did the bicycle fall over? Because it was two-tired.",
  "I used to play piano by ear, but now I use my hands.",
  "Why did the math book look sad? Because it had too many problems.",
  "What's orange and sounds like a parrot? A carrot.",
  "Why did the tomato turn red? Because it saw the salad dressing.",
  "What do you get when you cross a snowman and a vampire? Frostbite.",
  "How does a penguin build its house? Igloos it together.",
  "Did you hear about the kidnapping at the playground? They woke up.",
  "I'm on a seafood diet. I see food, and I eat it.",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
  "Did you hear about the claustrophobic astronaut? He just needed a little space.",
  "What do you call a bear that's stuck in the rain? A drizzly bear.",
  "Why did the scarecrow become a successful politician? Because he was outstanding in his field.",
  "How do you organize a space party? You 'planet'!",
  "Why did the computer catch a cold? It had too many windows open.",
  "What did one wall say to the other wall? 'I'll meet you at the corner!'",
  "Why don't oysters donate to charity? Because they are shellfish.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
"Why did the bicycle fall over? Because it was two-tired.",
"What do you get when you cross a snowman and a dog? Frostbite.",
"Why don't skeletons fight each other? They don't have the guts.",
"How do you organize a space party? You 'planet'!",
"Why did the tomato turn red? Because it saw the salad dressing.",
"Did you hear about the cheese factory that exploded? There was nothing left but de-brie.",
"Why was the math book sad? Because it had too many problems.",
"I used to play piano by ear, but now I use my hands.",
"What's orange and sounds like a parrot? A carrot.",
"How does a penguin build its house? Igloos it together.",
"Did you hear about the kidnapping at the playground? They woke up.",
"I'm on a seafood diet. I see food, and I eat it.",
"Why did the golfer bring two pairs of pants? In case he got a hole in one.",
"Did you hear about the claustrophobic astronaut? He just needed a little space.",
"What do you call a bear that's stuck in the rain? A drizzly bear.",
"What did one wall say to the other wall? 'I'll meet you at the corner!'",
"Why don't oysters donate to charity? Because they are shellfish.",
"Parallel lines have so much in common. It's a shame they'll never meet.",
"Why did the computer catch a cold? It had too many windows open.",
"I used to play piano by ear, but now I use my hands.",
"What's orange and sounds like a parrot? A carrot.",
"How does a penguin build its house? Igloos it together."
];
let random=Math.floor(Math.random()*50)
let result=jokes[random];
// console.log(result);
document.getElementById("content").textContent = result